# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='title1',
            field=models.CharField(blank=True, default=b'', max_length=50, verbose_name=b'#1'),
        ),
        migrations.AlterField(
            model_name='result',
            name='title2',
            field=models.CharField(blank=True, default=b'', max_length=50, verbose_name=b'#2'),
        ),
        migrations.AlterField(
            model_name='result',
            name='title3',
            field=models.CharField(blank=True, default=b'', max_length=50, verbose_name=b'#3'),
        ),
    ]
