# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20171012_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='li.Person'),
        ),
    ]
