# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('li', '0008_auto_20171012_1721'),
        ('survey', '0003_auto_20171013_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='result',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='li.Person'),
        ),
        migrations.AddField(
            model_name='invite',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='survey.Result'),
        ),
        migrations.AddField(
            model_name='invite',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='li.Person'),
        ),
    ]
