# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20171013_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gr_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='result',
            name='title1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title1', to='survey.Book', to_field=b'gr_id', verbose_name=b'#1'),
        ),
        migrations.AlterField(
            model_name='result',
            name='title2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title2', to='survey.Book', to_field=b'gr_id', verbose_name=b'#2'),
        ),
        migrations.AlterField(
            model_name='result',
            name='title3',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title3', to='survey.Book', to_field=b'gr_id', verbose_name=b'#3'),
        ),
    ]
