# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20171016_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='form',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='person',
        ),
        migrations.AddField(
            model_name='result',
            name='is_invited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
