# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20171018_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amazon_url',
            field=models.URLField(blank=True, default=b'', max_length=1024),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(blank=True, default=b'', max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
    ]
