# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20171016_1709'),
        ('survey', '0007_book_author'),
    ]

    operations = [
    ]
