# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_result_read_nothing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, default=b'', max_length=400),
        ),
    ]
