# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('profile_url', models.URLField(unique=True)),
                ('tag', models.CharField(max_length=255)),
                ('is_introvert', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='li.Company')),
            ],
            options={
                'db_table': 'person',
                'verbose_name_plural': 'people',
            },
        ),
    ]
