# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('li', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
