# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('li', '0004_auto_20170511_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(blank=True, to='li.Skill'),
        ),
    ]
