# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('li', '0005_auto_20170511_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncorrectContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
