# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('li', '0006_incorrectcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incorrectcontact',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
