# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('li', '0007_auto_20170517_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_url',
            field=models.URLField(max_length=1024, unique=True),
        ),
    ]
