# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('li', '0008_auto_20171012_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
